version: '2'

services:
  backend:
    build: ./api
    container_name: tornado
    environment:
      - PYTHONUNBUFFERED=1
    links:
      - redis
    depends_on:
      - redis
  redis:
    image: "redis:4-alpine"
    container_name: redis
    ports:
     - "6379"
    volumes:
      - ./data:/data
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile-prod
    container_name: nginx
    volumes:
      - /etc/ssl/certs:/etc/ssl/certs
      - /etc/ssl/private/:/etc/ssl/private
    ports:
      - 80:80
      - 443:443
    links:
      - backend
    depends_on:
      - backend
