version: '2'

services:
  backend:
    build: ./api
    container_name: tornado
    environment:
      - PYTHONUNBUFFERED=1
#    ports:
#      - 8080:80
    links:
      - redis
    depends_on:
      - redis
  react:
    build: ./frontend
    container_name: react
#    ports:
#      - 80:3000
  redis:
    image: "redis:4"
    container_name: redis
    ports:
     - "6379"
  proxy:
    build: ./proxy
    container_name: nginx
    ports:
      - 80:80
    links:
      - react
      - backend
    depends_on:
      - react
      - backend
